services:
  caddy:
    image: caddy:2.11.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "8443:8443"
    volumes:
      - $PWD/caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy
    depends_on:
      - app

  database:
    image: postgres:18
    restart: unless-stopped
    shm_size: 128mb
    env_file: .env.postgres
    networks:
      - proxy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wasdetchan"]
      interval: 1s
      timeout: 1s
      retries: 5

  app:
    restart: unless-stopped
    networks:
      - proxy
    build: 
      context: .
      network: host
    volumes:
      - /public:/public
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
    environment:
      GIN_MODE: debug

networks:
  proxy:
    driver: bridge
  ip6net:
     enable_ipv6: true
     ipam:
       config:
         - subnet: 2001:db8::/64

volumes:
  caddy_data:
  caddy_config:
