// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Receipt struct {
	UserID pgtype.UUID
	Fpd    int64
	Total  int64
	Time   pgtype.Timestamp
	Optype int16
	Place  string
}

type User struct {
	ID      pgtype.UUID
	Name    string
	Email   string
	IsAdmin bool
}
