// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// reference colors:
// foreground                      #d3c6aa
// background                      #272e33
// selection_foreground            #9da9a0
// selection_background            #464e53
//
// cursor                          #d3c6aa
// cursor_text_color               #2e383c
//
// url_color                       #7fbbb3
//
// active_border_color             #a7c080
// inactive_border_color           #4f5b58
// bell_border_color               #e69875
// visual_bell_color               none
//
// wayland_titlebar_color          system
// macos_titlebar_color            system
//
// active_tab_background           #272e33
// active_tab_foreground           #d3c6aa
// inactive_tab_background         #374145
// inactive_tab_foreground         #9da9a0
// tab_bar_background              #2e383c
// tab_bar_margin_color            none
//
// mark1_foreground                #272e33
// mark1_background                #7fbbb3
// mark2_foreground                #272e33
// mark2_background                #d3c6aa
// mark3_foreground                #272e33
// mark3_background                #d699b6
//
// #: black
// color0                          #343f44
// color8                          #868d80
//
// #: red
// color1                          #e67e80
// color9                          #e67e80
//
// #: green
// color2                          #a7c080
// color10                         #a7c080
//
// #: yellow
// color3                          #dbbc7f
// color11                         #dbbc7f
//
// #: blue
// color4                          #7fbbb3
// color12                         #7fbbb3
//
// #: magenta
// color5                          #d699b6
// color13                         #d699b6
//
// #: cyan
// color6                          #83c092
// color14                         #83c092
//
// #: white
// color7                          #859289
// color15                         #9da9a0
func root() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`--green:#a7c080;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--blue:#7fbbb3;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--magenta:#d699b6;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--text-color:#d3c6aa;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--background-color:#272e33;`)
	templ_7745c5c3_CSSID := templ.CSSID(`root`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func body() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`background-color:var(--background-color);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--text-color);`)
	templ_7745c5c3_CSSID := templ.CSSID(`body`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func baseStyle() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\na:link {\n\tcolor: var(--blue);\n}\n\na:visited {\n\tcolor: var(--magenta);\n}\n  </style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
